### PR TITLE
add support for computer player at /match/player, added link for it to navbar

### PR DESCRIPTION
**Pull request by dylanleclair**

### CODE REVIEW

**Comment by dylanleclair** [comment]
need to do a bit of cleanup / TLC from a UI standpoint but it works !!!

**Review by jjiaang — COMMENTED** [review]
shits bussin

**Review by jjiaang — APPROVED** [review]
**shits COOL**

**Comment by ShehabSN** [comment]
my bad i did not see/forgot the requested review until I just saw Jason's comments  lol

**Pull request merged**
